# Generated by Django 4.1 on 2022-09-26 17:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_remove_pages_body_pages_content_alter_pages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
