# Generated by Django 4.1 on 2022-09-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_alter_pages_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ['-date']},
        ),
    ]
