# Generated by Django 4.1 on 2022-09-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_alter_pages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
