# Generated by Django 4.1 on 2022-09-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_pages_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
