# Generated by Django 4.1 on 2022-09-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_profiles_alter_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
