# Generated by Django 4.1 on 2022-09-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_delete_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
