# Generated by Django 4.1 on 2022-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
