# Generated by Django 4.1 on 2022-09-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
