# Generated by Django 4.1 on 2022-09-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_profile_image_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatar/default.png', upload_to='avatar'),
        ),
    ]
